- name: PLAY-1 TASK-1 nodejs intsallation
  ansible.builtin.import_role:
    name: common
    tasks_from: 
      - nodejs.yaml
      - user_creation.yaml
      - code_dnld_install.yaml
      - sft_service_dmn_rld.yaml
    
