- name: PLAY-1 TASK-1 nodejs intsallation
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: PLAY-1 TASK-2 nodejs intsallation
  ansible.builtin.import_role:
    name: common
    tasks_from: user_creation

- name: PLAY-1 TASK-3 nodejs intsallation
  ansible.builtin.import_role:
    name: common
    tasks_from: code_dnld_install
