- name: PLAY-1 TASK-1 nodejs intsallation
  ansible.builtin.import_role:
    name: common
    tasks_from: 
    - nodejs
    - user_creation
    - code_dnld_install
    - sft_service_dmn_rld


    

    
