- name: Directory Creation
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download application code
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{software}}.zip
    dest: /tmp/{{software}}.zip

- name: unzip downloaded code
  ansible.builtin.unarchive:
    src: /tmp/{{software}}.zip
    dest: /app
    remote_src: yes

- name: npm installation
  community.general.npm:
    name: npm
    path: /app