- name: "get the catalogue entries count"
  ansible.builtin.shell:  mongo --host mongodb.hellodns.xyz --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: products_count
  when: software == "catalogue"

- name: "get the user entries count"
  ansible.builtin.shell:  mongo --host mongodb.hellodns.xyz --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: users_count
  when: software == "user"

- name: "load catalogue data"
  ansible.builtin.shell: "mongo --host mongodb.hellodns.xyz < /app/schema/{{software}}.js"
  when: software == "catalogue" and products_count.stdout == "0"  # keep double quotes
  #ignore_errors: true

- name: "load user data"
  ansible.builtin.shell: "mongo --host mongodb.hellodns.xyz < /app/schema/{{software}}.js"
  when: software == "user" and users_count.stdout == "0"  # keep double quotes
  #ignore_errors: true